# -*- coding: utf-8 -*-
"""chart-building.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YMuneTOFv3CWGrVuYvBLk0mHh_Zm8G1C
"""

from IPython.display import display,HTML
import random
def colored_header(string):
    randi=random.randint(1,99999)
    display(HTML("""
<style>
    @import 'https://fonts.googleapis.com/css?family=Akronim';
    #colored_header"""+str(randi)+\
""" {color:slategray; font-family:Akronim; 
                      text-shadow:4px 4px 4px #aaa; padding-left:20px;}
</style>
<script>
var tc=setInterval(function() {
    var doc1=document.getElementById('colored_header"""+str(randi)+\
"""');
    var now=new Date().getTime();
    var sec=Math.floor((now%(1000*60))/1000);
    var col='rgb('+(10+Math.abs(245-8*sec))+',0,'+(255-Math.abs(245-8*sec))+')';
    doc1.style.color=col; },1000);
</script>
<h1 id='colored_header"""+str(randi)+"""'>📑 """+string+"""</h1>"""))
colored_header('Barh Charts from HTML Elements')

# Commented out IPython magic to ensure Python compatibility.
# %%writefile barh_chart.py
# from IPython.display import display,HTML
# 
# def barh_chart(data,chart_title,width,
#                font_size=16,
#                font_family='Wallpoet',
#                background_color='#ff355e'):
#     dmax=max(data)
#     html_str="""<style>
#     @import 'https://fonts.googleapis.com/css?family="""+\
#     font_family+\
#     """'; .div_params {padding:5px; width:"""+\
#     str(round(width/100*dmax))+\
#     """px; text-align:right; text-shadow:4px 4px 4px slategray; 
#     color:lightgray; font-size:"""+\
#     str(font_size)+\
#     """px; font-family:"""+\
#     font_family+\
#     """; background:linear-gradient(180deg,lightgray 0%,silver 33%,
#     slategray 67%, darkslategray 100%);}
#     .div_params_in {background:"""+\
#     background_color+\
#     """; padding:5px; margin:3px;}
#     #div_h2 {text-shadow:4px 4px 4px slategray; color:"""+\
#     background_color+"""; font-family:"""+font_family+\
#     """;}</style>
#     <div class='div_params'><h2 id='div_h2'>"""+\
#     chart_title+"""</h2>"""
#     for i in range(len(data)):
#         html_str+="""<div class='div_params_in' style='width:"""+\
#                   str(.9*width/100*data[i])+"""px;'>"""+\
#                   str(data[i])+"""</div>"""
#     html_str+="""</div><br/>"""
#     display(HTML(html_str))

# Commented out IPython magic to ensure Python compatibility.
# %run barh_chart.py
width=1200; data=[4,12,21,38,42,55]
chart_title='Building Bar Charts'
barh_chart(data,chart_title,width)

colored_header('Barh Charts from D3 Elements')

# Commented out IPython magic to ensure Python compatibility.
# %%writefile d3barh_chart.py
# from IPython.display import display,HTML
# import random
# 
# def d3barh_chart(data,chart_title,width,height,
#                  color='silver',cmap='Sinebow',
#                  font_size=24,font_family='Wallpoet'):
#     html_str="""
# <style>
# @import 'https://fonts.googleapis.com/css?family="""+\
# font_family+"""';
# #d3barchart_title {color:"""+color+"""; font-family:"""+\
# font_family+"""; font-size:"""+str(font_size)+"""px;}
# #d3barchart {width:98%; height:95%;}
# </style>
# <script src='https://d3js.org/d3.v6.min.js'></script>
# <div id='d3barchart'><text id='d3barchart_title'></text></div>
# <script>
# var data="""+str(data)+""";
# var tc=setInterval(function(){
#     var now=new Date().getTime();
#     var width=Math.min(window.screen.width,window.innerWidth);
#     var div=d3.select('#d3barchart');
#     div.select('#d3barchart_title')
#        .text('"""+chart_title+"""');
#     div.style('text-align','right')
#        .style('text-shadow','3px 3px 3px slategray')
#        .style('padding','5px')
#        .style('color',d3.interpolate"""+cmap+"""(now/1000000))
#        .style('background',d3.interpolate"""+cmap+"""(now/1000000));
#     var x=d3.scaleLinear().domain([0,d3.max(data)]).range([0,.9*width])
#     div.selectAll('div').data(data).join('div')
#        .style('background','"""+color+"""')
#        .style('padding','5px').style('margin','3px')
#        .style('width',d=>x(d)+'px')
#        .style('font-family','"""+font_family+"""')
#        .style('font-size','"""+str(font_size)+"""px')
#        .text(d=>d);},100);
# </script>"""
#     file='d3barh_chart'+str(random.uniform(0,9999999))+'.html'
#     with open(file,'w') as f:
#          f.write(html_str); f.close()
#     string="""<div id='html_string2'><iframe src='"""+\
#            file+"""' height="""+str(height)+\
#            """ width="""+str(width)+"""></iframe></div>"""
#     display(HTML(string))

# Commented out IPython magic to ensure Python compatibility.
# %run d3barh_chart.py
width=680; height=280
data=[4,12,21,38,42,55]
chart_title='An Example of D3 Bar Charts'
d3barh_chart(data,chart_title,width,height)

d3barh_chart(data,chart_title,width,height,
             'white','Turbo',18,'Orbitron')