# -*- coding: utf-8 -*-
"""d3py-plotting.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tsCnemc0dhlqMC7OFjJQuda-vDf6KGhP
"""

# Commented out IPython magic to ensure Python compatibility.
# %run ../input/python-recipes/dhtml.py
dhtml('D3Scatter XY & CSV')

# Commented out IPython magic to ensure Python compatibility.
# %run ../input/python-recipes/d3scatter_xy_csv.py
csv_url='https://olgabelitskaya.github.io/castle.csv'
d3scatter_xy_csv(csv_url,'x','z',2,'ghostwhite','steelblue',600,300)

csv_url='https://olgabelitskaya.github.io/beethoven.csv'
d3scatter_xy_csv(csv_url,'x','z',.7,'black','slategray',600,700)

dhtml('D3 Bar Charts & Lists')

# Commented out IPython magic to ensure Python compatibility.
# %run ../input/python-recipes/d3barchart_list.py
num_list=[1,5,14,16,8,22,7,11,13,4,26,2,30,19,3,
          2,4,8,6,17,1,4,5,2,3,23,18,14,11,5]
d3barchart_list(num_list)