# -*- coding: utf-8 -*-
"""external-geodata.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ybdmDKamIWu5XNC2iHp3gKNHf_cz9Q8D
"""

install.packages('osmar')
library(ggmap); library(osmar)
library(tidyverse); library(IRdisplay)
api<-osmsource_api(url="https://api.openstreetmap.org/api/0.6/")
display_html("<style>
@import 'https://fonts.googleapis.com/css?family=Smokum&effect=3d';      
</style>")

display_html("<h1 class='font-effect-3d' 
style='color:#ff355e; font-family:Smokum;'>
GeoData Extraction from External Sources</h1>")

cbox=c(11.579000,48.150000,11.583000,48.154000)
osmmap<-get_map(location=cbox,source="osm")

options(repr.plot.width=9,repr.plot.height=9)
ggmap(osmmap);

box<-corner_bbox(11.579000,48.150000,
                 11.583000,48.154000)
gschw<-get_osm(box,source=api)

display_html("<h1 class='font-effect-3d' 
style='color:#ff355e; font-family:Smokum;'>
GeoData Exploration</h1>")

str(gschw)

node_tags<-sort(unique(gschw$nodes$tags$k))
print(node_tags)

way_tags<-sort(unique(gschw$ways$tags$k))
print(way_tags)

users<-sort(unique(gschw$nodes$attrs$user))
print(users)

display_html("<h1 class='font-effect-3d' 
style='color:#ff355e; font-family:Smokum;'>
GeoData Plotting</h1>")

plot(gschw,way_args=list(col='steelblue'))
grid()

tss<-find(gschw,node(tags(v=="traffic_signals")))
bss<-find(gschw,node(tags(v%agrep%"bus")))
hws<-find(gschw,way(tags(k=="highway")))
hws<-find_down(gschw,way(hws))
tus<-find(gschw,way(tags(k=="tunnel")))
tus<-find_down(gschw,way(tus))
tss_gschw<-subset(gschw,node_ids=tss)
bss_gschw<-subset(gschw,node_ids=bss)
hws_gschw<-subset(gschw,ids=hws)
hws_gschw<-as_sp(hws_gschw,"lines") 
tus_gschw<-subset(gschw,ids=tus)

plot(hws_gschw,xlab="lon",ylab="lat",
     col="steelblue")
plot_ways(tus_gschw,add=TRUE,col="magenta")
plot_nodes(tss_gschw,add=TRUE,col="red")
plot_nodes(bss_gschw,add=TRUE,col="blue")
box(); grid()

bs<-find(gschw,way(tags(k=="building")))
bs<-find_down(gschw,way(bs))
bs_gschw<-subset(gschw,ids=bs)
bs_poly<-as_sp(bs_gschw,"polygons")
bss_gschw<-as_sp(bss_gschw,"points")

plot(bs_poly,xlab="lon",ylab="lat",
     col="lightsteelblue")
plot(hws_gschw,add=TRUE,col="blue")
plot(bss_gschw,add=TRUE,col="red",pch=12)
grid(); box();