# -*- coding: utf-8 -*-
"""fun-vs-serious-pyplotting.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xy_9d3W2OvruLbcncFu-175tixzs9qbj
"""

# Commented out IPython magic to ensure Python compatibility.
# %run ../input/python-recipes/dhtml.py
dhtml('Code Modules','#3636ff')

import numpy as np,sympy as sp
import pandas as pd,pylab as pl

dhtml('Don`t Tell Me That You Don`t Like This',
      '#3636ff')

pl.xkcd()
df=pd.DataFrame(np.random.randn(30,4),
                columns=['1','2','3','4'])
df['A&B&C']=pd.Series(
    10*['A']+10*['B']+10*['C'])
df.boxplot(by='A&B&C',figsize=(11,7))
pl.tight_layout();

pi=np.pi 
t=np.arange(0,2*pi,.1**4)
def col(): 
    return [np.append([0],np.random.random(2))]
def f(t): 
    return np.exp(np.cos(t)**2+np.sin(t))-3*np.cos(4*t)
def fx(k,t): 
    return .1*(k+1)*f(t)*np.cos(t)
def fy(k,t): 
    return .1*(k+1)*f(t)*np.sin(t)
pl.figure(figsize=(10,10))
ax=pl.gca(); ax.set_facecolor('whitesmoke')
[pl.scatter(fx(i,t),fy(i,t),s=.1**3,c=col()) 
 for i in range(12)];

from mpl_toolkits.mplot3d import Axes3D
f=pl.figure(figsize=(10,10))
ax=f.add_subplot(111,projection='3d')
X=np.linspace(-7,7,128); X,Y=np.meshgrid(X,X)
Z1=1/2*X**2+1/8*Y**2; Z1[Z1>6]=np.nan
Z2=1/8*X**2-1/18*Y**2
Z2[Z2<-6]=np.nan; Z2[Z2>6]=np.nan
label1='$x^2/1^2+y^2/2^2=2 \cdot z$'
label2='$x^2/2^2-y^2/3^2=2 \cdot z$'
ax.plot_wireframe(X,Y,Z1,alpha=.7,
                  colors='#36ff36')
ax.plot_wireframe(X,Y,Z2,alpha=.4,
                  colors='#3636ff')
ax.text(2,7,7,label1,
        color='#36ff36',fontsize=15)
ax.text(-12,-7,-7,label2,
        color='#3636ff',fontsize=15)
ax.xaxis.pane.fill,ax.yaxis.pane.fill,\
ax.zaxis.pane.fill=False,False,False
ax.set_xlim(-7,7)
ax.set_ylim(-7,7); ax.set_zlim(-7,7);

dhtml('In Progress','#3636ff')