# -*- coding: utf-8 -*-
"""lightning-practice.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kSCGLPHwFSULqLEkp4WiEL4iV3JBrkI0
"""

!pip install lightning-python --user

# Commented out IPython magic to ensure Python compatibility.
# %run ../input/python-recipes/dhtml.py
dhtml('File Writing')

# Commented out IPython magic to ensure Python compatibility.
# %%writefile light_plots.py
# import numpy as np,pandas as pd,pylab as pl
# from IPython.core.display import display
# from sklearn.preprocessing import \
# MinMaxScaler as mms
# from lightning import Lightning
# lgn=Lightning(ipython=True,local=True)
# 
# def light_line(file_path,file_name,lw,cmap,
#                w=500,h=300):
#     series=np.loadtxt(
#         file_path+file_name,delimiter=',',skiprows=1)
#     if series.shape[0]>series.shape[1]:
#         series=series.T
#     c=np.array([pl.cm.get_cmap(cmap)(i/3)[:3]
#                 for i in range(3)])
#     c=np.array(255*c,dtype='int32')
#     viz=lgn.line(series,color=c,thickness=lw,
#                  width=w,height=h)
#     display(viz)
#     
# def light_scatter(file_path,file_name,x,y,
#                   value,size,label,cmap,
#                   w=500,h=300,sep='\t'):
#     data=pd.read_csv(file_path+file_name,sep=sep)
#     size_array=data[size].values.reshape(-1,1)
#     scaler=mms(feature_range=(3,15)).fit(size_array)
#     size_array=scaler.transform(size_array)
#     viz=lgn.scatter(data[x].values,data[y].values,
#                     values=data[value].values,
#                     labels=data[label].values,
#                     size=size_array.reshape(-1),
#                     colormap=cmap,width=w,height=h)
#     display(viz)

dhtml('File Usage')

# Commented out IPython magic to ensure Python compatibility.
# %run light_plots.py
file_path='../input/image-examples-for-mixed-styles/'
file_name='beethoven.csv'
light_line(file_path,file_name,1,'hsv')

file_path='../input/geodata-for-exercises/'
file_name='huge_cities.tsv'
y='latitude'; x='longitude'; 
value='growth'; size='y_2014'; 
label='city'; cmap='Spectral'
light_scatter(file_path,file_name,x,y,
              value,size,label,cmap)

dhtml('In Progress')