# -*- coding: utf-8 -*-
"""styling-recipes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Dc73Hb0SNkJtj8jDhVA_U7ZvAO7ycdU7

# 📑 Notebook Styling
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile notebook_style.py
# from IPython.core.display import display,HTML
# 
# def notebook_style(prompt_font='Wallpoet',
#                    prompt_in_color='#ff9966',
#                    prompt_out_color='#50bfe6',
#                    warn_font='Wallpoet',
#                    warn_color='#ff355e',
#                    out_font='Roboto',
#                    out_color='#50bfe6',
#                    background_out_color='whitesmoke',
#                    heading_text_shadow=True,
#                    span_text_shadow=True):
#     style_str="""<style>"""+\
#     """@import 'https://fonts.googleapis.com/css?family="""+\
#     prompt_font+"""|"""+out_font+"""|"""+warn_font+"""'; """
#     if heading_text_shadow==True:
#         style_str+="""h1,h2,h3,h4,h5,h6 """+\
#                    """{text-shadow:4px 4px 4px #aaa;}"""
#     if span_text_shadow==True:
#         style_str+="""span {color:black; """+\
#                    """text-shadow:4px 4px 4px #aaa;}"""
#     style_str+="""div.warn {background-color:"""+\
#                background_out_color+"""; color:"""+\
#                warn_color+"""; """+\
#                """font-family:"""+warn_font+""";}"""
#     style_str+="""div.output_area pre,div.output_stderr pre"""+\
#                """{background-color:"""+background_out_color+""";}"""
#     style_str+="""div.output_area pre,div.output_stderr pre,"""+\
#                """div.output_area,div.output_stderr"""+\
#                """{color:"""+out_color+"""; """+\
#                """font-family:"""+out_font+""";}"""
#     style_str+="""div.input_prompt {color:"""+\
#                prompt_in_color+"""; """+\
#                """font-family:"""+prompt_font+""";}"""
#     style_str+="""div.output_prompt {color:"""+\
#                prompt_out_color+"""; """+\
#                """font-family:"""+prompt_font+""";}"""   
#     style_str+="""</style>"""
#     display(HTML(style_str))

# Commented out IPython magic to ensure Python compatibility.
# %run notebook_style.py

# default options
notebook_style(prompt_font='Wallpoet',
               prompt_in_color='#ff9966',
               prompt_out_color='#50bfe6',
               warn_font='Wallpoet',
               warn_color='#ff355e',
               out_font='Roboto',
               out_color='#50bfe6',
               background_out_color='whitesmoke',
               heading_text_shadow=True,
               span_text_shadow=True)

"""# 📑 Result Checking"""

import pylab as pl
pl.plot([1.5,2.1,.3,1.1,2.7])
pl.title('Display output styling')

HTML("""<div class='warn'>Display warn styling</div>""")

"""# 📑 Sources"""

# Crayola colors
colors=['#FF355E','#FF6037','#FF9966','#FFCC33','#FFFF66',
        '#CCFF00','#66FF66','#50BFE6','#FF6EFF','#FF00CC']

HTML("""<style>"""+\
"""@import 'https://fonts.googleapis.com/css?family="""+\
"""Orbitron|Roboto|Wallpoet|Smokum|Akronim|Lobster|Ewert|"""+\
""";</style>"""+\
"""<p style='font-size:200%; font-family:Smokum'>Smokum</p><br/>"""+\
"""<p style='font-size:200%; font-family:Akronim'>Akronim</p><br/>"""+\
"""<p style='font-size:200%; font-family:Ewert'>Ewert</p><br/>"""+\
"""<p style='font-size:200%; font-family:Roboto'>Roboto</p><br/>"""+\
"""<p style='font-size:200%; font-family:Lobster'>Lobster</p><br/>"""+\
"""<p style='font-size:200%; font-family:Wallpoet'>Wallpoet</p><br/>"""+\
"""<p style='font-size:200%; font-family:Orbitron'>Orbitron</p><br/>""")

"""# 📑 In Progress"""