# -*- coding: utf-8 -*-
"""styling-recipes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Dc73Hb0SNkJtj8jDhVA_U7ZvAO7ycdU7

<span class='h1'>📑 Notebook Styling</span>
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile notebook_style.py
# from IPython.core.display import display,HTML
# 
# def notebook_style(span_h_font='Ewert',
#                    span_h_color='#ff3636',
#                    prompt_font='Ewert',
#                    prompt_in_color='#ff3636',
#                    prompt_out_color='#3636ff',
#                    warn_font='Roboto',
#                    warn_color='#ff36ff',
#                    out_font='Roboto',
#                    out_color='#3636ff',
#                    background_out_color='whitesmoke',
#                    span_text_shadow=True):
#     style_str="""<style>"""+\
#     """@import 'https://fonts.googleapis.com/css?family="""+\
#     prompt_font+"""|"""+out_font+"""|"""+warn_font+"""'; """
#     if span_text_shadow==True:
#         style_str+="""span {color:black; """+\
#                    """text-shadow:4px 4px 4px #aaa;}"""
#     style_str+="""div.alert {text-shadow:4px 4px 4px #aaa;}"""
#     style_str+="""span.h1,span.h2,span.h3,"""+\
#                """span.h4,span.h5,span.h6 """+\
#                """{color:"""+span_h_color+"""; """+\
#                """font-family:"""+span_h_font+""";} """
#     style_str+="""div.warn {background-color:"""+\
#                background_out_color+"""; color:"""+\
#                warn_color+"""; font-size:110%; """+\
#                """font-family:"""+warn_font+""";} """
#     for el in ["""div.output_area pre""",
#                """div.output_stderr pre"""
#                """div.output_subarea""",
#                """div.output_html""",
#                """div.output_stderr"""]:
#         style_str+=el+"""{background-color:"""+\
#                    background_out_color+"""; color:"""+\
#                    out_color+"""; font-size:110%; """+\
#                    """font-family:"""+out_font+""";} """
#     style_str+="""div.input_prompt {color:"""+\
#                prompt_in_color+"""; """+\
#                """font-family:"""+prompt_font+""";} """
#     style_str+="""div.output_prompt {color:"""+\
#                prompt_out_color+"""; """+\
#                """font-family:"""+prompt_font+""";} """
#     style_str+=""".cm-s-ipython span.cm-comment {color:darkslategray;} """
#     style_str+=""".cm-s-ipython span.cm-def {color:#3636ff;} """
#     style_str+=""".cm-s-ipython span.cm-operator {color:#ff36ff;} """
#     style_str+=""".cm-s-ipython span.cm-keyword {color:darkgreen;} """
#     style_str+=""".cm-s-ipython span.cm-string {color:#ff3636;} """
#     style_str+="""</style>"""
#     display(HTML(style_str))

# Commented out IPython magic to ensure Python compatibility.
# %run notebook_style.py

# default options
notebook_style(span_h_font='Ewert',
               span_h_color='#ff3636',
               prompt_font='Ewert',
               prompt_in_color='#ff3636',
               prompt_out_color='#3636ff',
               warn_font='Roboto',
               warn_color='#ff36ff',
               out_font='Roboto',
               out_color='#3636ff',
               background_out_color='whitesmoke',
               span_text_shadow=True)

"""<span class='h1'> 📑 Result Checking</span>"""

# Commented out IPython magic to ensure Python compatibility.
# %%html
# <span class='h4'> It works in Markdown cells as well.</span>

import pylab as pl
pl.plot([1.5,2.1,.3,1.1,2.7])
pl.title('Display output styling')

HTML("""<div class='warn'>Display warn styling</div>""")

"""<span class='h1'>📑 Built-In Styling</span>
```python
s='Python syntax highlighting in Markdown cells'
print(s)
```
```javascript
var s='JavaScript syntax highlighting in Markdown cells';
const m=100;
```
"""

# Commented out IPython magic to ensure Python compatibility.
# %%html
# <div class='alert alert-block alert-info'>
# <b>Tips:</b> Alert-info notes can 
#     be used for tips and notes.</div>
# <div class='alert alert-block alert-success'>
# <b>Success:</b> This alert box indicates 
#     a successful or positive action.</div>
# <div class='alert alert-block alert-warning'>
# <b>Warnings:</b> These elements are convenient 
#     to display warning messages.</div>
# <div class='alert alert-block alert-danger'>
# <b>Dangers:</b> This alert box indicates 
#     a dangerous or potentially negative action.</div>

"""<span class='h1'>📑 Sources</span>"""

# Crayola colors
colors=['#FF355E','#FF6037','#FF9966','#FFCC33','#FFFF66',
        '#CCFF00','#66FF66','#50BFE6','#FF6EFF','#FF00CC']

# https://fonts.google.com/
HTML("""<style>"""+\
"""@import 'https://fonts.googleapis.com/css?family="""+\
"""Orbitron|Roboto|Wallpoet|Smokum|Akronim|Lobster|Ewert|"""+\
""";</style>"""+\
"""<text style='font-size:200%; font-family:Smokum'>Smokum </text>"""+\
"""<text style='font-size:200%; font-family:Akronim'>Akronim </text>"""+\
"""<text style='font-size:200%; font-family:Ewert'>Ewert </text>"""+\
"""<text style='font-size:200%; font-family:Roboto'>Roboto </text><br/><br/>"""+\
"""<text style='font-size:200%; font-family:Lobster'>Lobster </text>"""+\
"""<text style='font-size:200%; font-family:Wallpoet'>Wallpoet </text>"""+\
"""<text style='font-size:200%; font-family:Orbitron'>Orbitron </text>""")

"""<span class='h1'>📑 In Progress</span>"""